spring:
    application:
        name: eureka-server
    
server:
    port: 8760

eureka:
    client:
        register-with-eureka: false # Le dice que no se registre a si mismo
        fetch-registry: false # Le dice al servidor eureka que no busque otras rutas de otros
                              # rutas de otros
                              # servidores eureka porque es el unico que tenemos